// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/v2/agentV2.proto

package protov2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigStatus int32

const (
	// The value of status field is not set.
	ConfigStatus_UNSET ConfigStatus = 0
	// Agent is currently applying the remote config that it received earlier.
	ConfigStatus_APPLYING ConfigStatus = 1
	// Remote config was successfully applied by the Agent.
	ConfigStatus_APPLIED ConfigStatus = 2
	// Agent tried to apply the config received earlier, but it failed.
	// See error_message for more details.
	ConfigStatus_FAILED ConfigStatus = 3
)

// Enum value maps for ConfigStatus.
var (
	ConfigStatus_name = map[int32]string{
		0: "UNSET",
		1: "APPLYING",
		2: "APPLIED",
		3: "FAILED",
	}
	ConfigStatus_value = map[string]int32{
		"UNSET":    0,
		"APPLYING": 1,
		"APPLIED":  2,
		"FAILED":   3,
	}
)

func (x ConfigStatus) Enum() *ConfigStatus {
	p := new(ConfigStatus)
	*p = x
	return p
}

func (x ConfigStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_agentV2_proto_enumTypes[0].Descriptor()
}

func (ConfigStatus) Type() protoreflect.EnumType {
	return &file_proto_v2_agentV2_proto_enumTypes[0]
}

func (x ConfigStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigStatus.Descriptor instead.
func (ConfigStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{0}
}

type AgentCapabilities int32

const (
	// The capabilities field is unspecified.
	AgentCapabilities_UnspecifiedAgentCapability AgentCapabilities = 0
	// The Agent can accept continuous pipeline configuration from the Server.
	AgentCapabilities_AcceptsContinuousPipelineConfig AgentCapabilities = 1
	// The Agent can accept instance configuration from the Server.
	AgentCapabilities_AcceptsInstanceConfig AgentCapabilities = 2
	// The Agent can accept onetime pipeline configuration from the Server.
	AgentCapabilities_AcceptsOnetimePipelineConfig AgentCapabilities = 4
)

// Enum value maps for AgentCapabilities.
var (
	AgentCapabilities_name = map[int32]string{
		0: "UnspecifiedAgentCapability",
		1: "AcceptsContinuousPipelineConfig",
		2: "AcceptsInstanceConfig",
		4: "AcceptsOnetimePipelineConfig",
	}
	AgentCapabilities_value = map[string]int32{
		"UnspecifiedAgentCapability":      0,
		"AcceptsContinuousPipelineConfig": 1,
		"AcceptsInstanceConfig":           2,
		"AcceptsOnetimePipelineConfig":    4,
	}
)

func (x AgentCapabilities) Enum() *AgentCapabilities {
	p := new(AgentCapabilities)
	*p = x
	return p
}

func (x AgentCapabilities) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCapabilities) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_agentV2_proto_enumTypes[1].Descriptor()
}

func (AgentCapabilities) Type() protoreflect.EnumType {
	return &file_proto_v2_agentV2_proto_enumTypes[1]
}

func (x AgentCapabilities) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCapabilities.Descriptor instead.
func (AgentCapabilities) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{1}
}

type RequestFlags int32

const (
	RequestFlags_RequestFlagsUnspecified RequestFlags = 0
	// Must be set if this request contains full state
	RequestFlags_FullState RequestFlags = 1 // bits before 2^16 (inclusive) are reserved for future official fields
)

// Enum value maps for RequestFlags.
var (
	RequestFlags_name = map[int32]string{
		0: "RequestFlagsUnspecified",
		1: "FullState",
	}
	RequestFlags_value = map[string]int32{
		"RequestFlagsUnspecified": 0,
		"FullState":               1,
	}
)

func (x RequestFlags) Enum() *RequestFlags {
	p := new(RequestFlags)
	*p = x
	return p
}

func (x RequestFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_agentV2_proto_enumTypes[2].Descriptor()
}

func (RequestFlags) Type() protoreflect.EnumType {
	return &file_proto_v2_agentV2_proto_enumTypes[2]
}

func (x RequestFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestFlags.Descriptor instead.
func (RequestFlags) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{2}
}

type ServerCapabilities int32

const (
	// The capabilities field is unspecified.
	ServerCapabilities_UnspecifiedServerCapability ServerCapabilities = 0
	// The Server can remember agent attributes.
	ServerCapabilities_RembersAttribute ServerCapabilities = 1
	// The Server can remember continuous pipeline config status.
	ServerCapabilities_RembersContinuousPipelineConfigStatus ServerCapabilities = 2
	// The Server can remember instance config status.
	ServerCapabilities_RembersInstanceConfigStatus ServerCapabilities = 4
	// The Server can remember onetime pipeline config status.
	ServerCapabilities_RembersOnetimePipelineConfigStatus ServerCapabilities = 8
)

// Enum value maps for ServerCapabilities.
var (
	ServerCapabilities_name = map[int32]string{
		0: "UnspecifiedServerCapability",
		1: "RembersAttribute",
		2: "RembersContinuousPipelineConfigStatus",
		4: "RembersInstanceConfigStatus",
		8: "RembersOnetimePipelineConfigStatus",
	}
	ServerCapabilities_value = map[string]int32{
		"UnspecifiedServerCapability":           0,
		"RembersAttribute":                      1,
		"RembersContinuousPipelineConfigStatus": 2,
		"RembersInstanceConfigStatus":           4,
		"RembersOnetimePipelineConfigStatus":    8,
	}
)

func (x ServerCapabilities) Enum() *ServerCapabilities {
	p := new(ServerCapabilities)
	*p = x
	return p
}

func (x ServerCapabilities) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCapabilities) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_agentV2_proto_enumTypes[3].Descriptor()
}

func (ServerCapabilities) Type() protoreflect.EnumType {
	return &file_proto_v2_agentV2_proto_enumTypes[3]
}

func (x ServerCapabilities) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCapabilities.Descriptor instead.
func (ServerCapabilities) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{3}
}

type ResponseFlags int32

const (
	ResponseFlags_ResponseFlagsUnspecified ResponseFlags = 0
	// ReportFullState flag can be used by the Server if the Client did not include
	// some sub-message in the last AgentToServer message (which is an allowed
	// optimization) but the Server detects that it does not have it (e.g. was
	// restarted and lost state).
	ResponseFlags_ReportFullState ResponseFlags = 1
	// FetchContinuousPipelineConfigDetail can be used by the Server to tell Agent to fetch continuous pipeline config details by FetchConfig api,
	// HB response ConfigDetail will not contains details.
	ResponseFlags_FetchContinuousPipelineConfigDetail ResponseFlags = 2
	// like FetchContinuousPipelineConfigDetail, but for instance config.
	ResponseFlags_FetchInstanceConfigDetail ResponseFlags = 4 // bits before 2^16 (inclusive) are reserved for future official fields
)

// Enum value maps for ResponseFlags.
var (
	ResponseFlags_name = map[int32]string{
		0: "ResponseFlagsUnspecified",
		1: "ReportFullState",
		2: "FetchContinuousPipelineConfigDetail",
		4: "FetchInstanceConfigDetail",
	}
	ResponseFlags_value = map[string]int32{
		"ResponseFlagsUnspecified":            0,
		"ReportFullState":                     1,
		"FetchContinuousPipelineConfigDetail": 2,
		"FetchInstanceConfigDetail":           4,
	}
)

func (x ResponseFlags) Enum() *ResponseFlags {
	p := new(ResponseFlags)
	*p = x
	return p
}

func (x ResponseFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_agentV2_proto_enumTypes[4].Descriptor()
}

func (ResponseFlags) Type() protoreflect.EnumType {
	return &file_proto_v2_agentV2_proto_enumTypes[4]
}

func (x ResponseFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseFlags.Descriptor instead.
func (ResponseFlags) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{4}
}

type AgentGroupTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentGroupTag) Reset() {
	*x = AgentGroupTag{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentGroupTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGroupTag) ProtoMessage() {}

func (x *AgentGroupTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGroupTag.ProtoReflect.Descriptor instead.
func (*AgentGroupTag) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{0}
}

func (x *AgentGroupTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentGroupTag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Define the Config information carried in the request
type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                             // Required, Config's unique identification
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                                                      // Required, Config's version number or hash code
	Status        ConfigStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=configserver.proto.v2.ConfigStatus" json:"status,omitempty"`                                // Config's status
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                                                       // Optional error message
	Extra         map[string][]byte      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigInfo) GetStatus() ConfigStatus {
	if x != nil {
		return x.Status
	}
	return ConfigStatus_UNSET
}

func (x *ConfigInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigInfo) GetExtra() map[string][]byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Define Agent's basic attributes
type AgentAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       []byte                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                                           // Agent's version
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                                                                                     // Agent's ip
	Hostname      []byte                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                         // Agent's hostname
	Hostid        []byte                 `protobuf:"bytes,4,opt,name=hostid,proto3" json:"hostid,omitempty"`                                                                             // Agent's hostid  https://opentelemetry.io/docs/specs/semconv/attributes-registry/host/
	Extras        map[string][]byte      `protobuf:"bytes,100,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Agent's other attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAttributes) Reset() {
	*x = AgentAttributes{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAttributes) ProtoMessage() {}

func (x *AgentAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAttributes.ProtoReflect.Descriptor instead.
func (*AgentAttributes) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{2}
}

func (x *AgentAttributes) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *AgentAttributes) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *AgentAttributes) GetHostname() []byte {
	if x != nil {
		return x.Hostname
	}
	return nil
}

func (x *AgentAttributes) GetHostid() []byte {
	if x != nil {
		return x.Hostid
	}
	return nil
}

func (x *AgentAttributes) GetExtras() map[string][]byte {
	if x != nil {
		return x.Extras
	}
	return nil
}

// Agent sends requests to the ConfigServer to get config updates and receive commands.
type HeartbeatRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RequestId                 []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SequenceNum               uint64                 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`                                             // Increment every request, for server to check sync status
	Capabilities              uint64                 `protobuf:"varint,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                                              // Bitmask of flags defined by AgentCapabilities enum
	InstanceId                []byte                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                 // Required, Agent's unique identification, consistent throughout the process lifecycle
	AgentType                 string                 `protobuf:"bytes,5,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`                                                    // Required, Agent's type(ilogtail, ..)
	Attributes                *AgentAttributes       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`                                                                   // Agent's basic attributes
	Tags                      []*AgentGroupTag       `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                                                               // Agent's tags
	RunningStatus             string                 `protobuf:"bytes,8,opt,name=running_status,json=runningStatus,proto3" json:"running_status,omitempty"`                                        // Human readable running status
	StartupTime               int64                  `protobuf:"varint,9,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"`                                             // Required, Agent's startup time
	ContinuousPipelineConfigs []*ConfigInfo          `protobuf:"bytes,10,rep,name=continuous_pipeline_configs,json=continuousPipelineConfigs,proto3" json:"continuous_pipeline_configs,omitempty"` // Information about the current continuous pipeline configs held by the Agent
	InstanceConfigs           []*ConfigInfo          `protobuf:"bytes,11,rep,name=instance_configs,json=instanceConfigs,proto3" json:"instance_configs,omitempty"`                                 // Information about the current instance configs held by the Agent
	OnetimePipelineConfigs    []*ConfigInfo          `protobuf:"bytes,12,rep,name=onetime_pipeline_configs,json=onetimePipelineConfigs,proto3" json:"onetime_pipeline_configs,omitempty"`          // Information about onetime pipeline configs history
	Flags                     uint64                 `protobuf:"varint,13,opt,name=flags,proto3" json:"flags,omitempty"`                                                                           // Predefined command flag
	Opaque                    []byte                 `protobuf:"bytes,14,opt,name=opaque,proto3" json:"opaque,omitempty"`                                                                          // Opaque data for extension
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *HeartbeatRequest) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *HeartbeatRequest) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *HeartbeatRequest) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *HeartbeatRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *HeartbeatRequest) GetAttributes() *AgentAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HeartbeatRequest) GetTags() []*AgentGroupTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningStatus() string {
	if x != nil {
		return x.RunningStatus
	}
	return ""
}

func (x *HeartbeatRequest) GetStartupTime() int64 {
	if x != nil {
		return x.StartupTime
	}
	return 0
}

func (x *HeartbeatRequest) GetContinuousPipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.ContinuousPipelineConfigs
	}
	return nil
}

func (x *HeartbeatRequest) GetInstanceConfigs() []*ConfigInfo {
	if x != nil {
		return x.InstanceConfigs
	}
	return nil
}

func (x *HeartbeatRequest) GetOnetimePipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.OnetimePipelineConfigs
	}
	return nil
}

func (x *HeartbeatRequest) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *HeartbeatRequest) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

// Define Config's detail
type ConfigDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                             // Required, Config's unique identification
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                                                      // Required, Config's version number or hash code
	Detail        []byte                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`                                                                         // Required, Config's detail
	Extra         map[string][]byte      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDetail) Reset() {
	*x = ConfigDetail{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDetail) ProtoMessage() {}

func (x *ConfigDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDetail.ProtoReflect.Descriptor instead.
func (*ConfigDetail) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigDetail) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigDetail) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ConfigDetail) GetExtra() map[string][]byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type CommandDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                             // Required, Command name
	Detail        []byte                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`                                                                         // Required, Command's detail
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                                              // After which the command can be safely removed from history
	Extra         map[string][]byte      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDetail) Reset() {
	*x = CommandDetail{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDetail) ProtoMessage() {}

func (x *CommandDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDetail.ProtoReflect.Descriptor instead.
func (*CommandDetail) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{5}
}

func (x *CommandDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDetail) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *CommandDetail) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CommandDetail) GetExtra() map[string][]byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

// ConfigServer's response to Agent's request
type HeartbeatResponse struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	RequestId                       []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CommonResponse                  *CommonResponse        `protobuf:"bytes,2,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`                                                        // Set common response
	Capabilities                    uint64                 `protobuf:"varint,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                                                                 // Bitmask of flags defined by ServerCapabilities enum
	ContinuousPipelineConfigUpdates []*ConfigDetail        `protobuf:"bytes,4,rep,name=continuous_pipeline_config_updates,json=continuousPipelineConfigUpdates,proto3" json:"continuous_pipeline_config_updates,omitempty"` // Agent's continuous pipeline config update status
	InstanceConfigUpdates           []*ConfigDetail        `protobuf:"bytes,5,rep,name=instance_config_updates,json=instanceConfigUpdates,proto3" json:"instance_config_updates,omitempty"`                                 // Agent's instance config update status
	OnetimePipelineConfigUpdates    []*CommandDetail       `protobuf:"bytes,6,rep,name=onetime_pipeline_config_updates,json=onetimePipelineConfigUpdates,proto3" json:"onetime_pipeline_config_updates,omitempty"`          // Agent's onetime pipeline config updates
	Flags                           uint64                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`                                                                                               // Predefined command flag
	Opaque                          []byte                 `protobuf:"bytes,8,opt,name=opaque,proto3" json:"opaque,omitempty"`                                                                                              // Opaque data for extension
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *HeartbeatResponse) GetCommonResponse() *CommonResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

func (x *HeartbeatResponse) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *HeartbeatResponse) GetContinuousPipelineConfigUpdates() []*ConfigDetail {
	if x != nil {
		return x.ContinuousPipelineConfigUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetInstanceConfigUpdates() []*ConfigDetail {
	if x != nil {
		return x.InstanceConfigUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetOnetimePipelineConfigUpdates() []*CommandDetail {
	if x != nil {
		return x.OnetimePipelineConfigUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *HeartbeatResponse) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

// API: /Agent/FetchConfig
// optional api for fetching configs details, but not by heartbeat response with config details, see README.
type FetchConfigRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RequestId                 []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	InstanceId                []byte                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                // Agent's unique identification
	ContinuousPipelineConfigs []*ConfigInfo          `protobuf:"bytes,3,rep,name=continuous_pipeline_configs,json=continuousPipelineConfigs,proto3" json:"continuous_pipeline_configs,omitempty"` // Information about the current continuous pipeline configs held by the Agent
	InstanceConfigs           []*ConfigInfo          `protobuf:"bytes,4,rep,name=instance_configs,json=instanceConfigs,proto3" json:"instance_configs,omitempty"`                                 // Information about the current instance configs held by the Agent
	OnetimePipelineConfigs    []*ConfigInfo          `protobuf:"bytes,5,rep,name=onetime_pipeline_configs,json=onetimePipelineConfigs,proto3" json:"onetime_pipeline_configs,omitempty"`          // Information about onetime pipeline configs history
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FetchConfigRequest) Reset() {
	*x = FetchConfigRequest{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigRequest) ProtoMessage() {}

func (x *FetchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{7}
}

func (x *FetchConfigRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *FetchConfigRequest) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *FetchConfigRequest) GetContinuousPipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.ContinuousPipelineConfigs
	}
	return nil
}

func (x *FetchConfigRequest) GetInstanceConfigs() []*ConfigInfo {
	if x != nil {
		return x.InstanceConfigs
	}
	return nil
}

func (x *FetchConfigRequest) GetOnetimePipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.OnetimePipelineConfigs
	}
	return nil
}

// ConfigServer response to Agent's config fetching request
type FetchConfigResponse struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	RequestId                       []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CommonResponse                  *CommonResponse        `protobuf:"bytes,2,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`
	ContinuousPipelineConfigUpdates []*ConfigDetail        `protobuf:"bytes,3,rep,name=continuous_pipeline_config_updates,json=continuousPipelineConfigUpdates,proto3" json:"continuous_pipeline_config_updates,omitempty"` // Agent's continuous pipeline config with details
	InstanceConfigUpdates           []*ConfigDetail        `protobuf:"bytes,4,rep,name=instance_config_updates,json=instanceConfigUpdates,proto3" json:"instance_config_updates,omitempty"`                                 // Agent's instance config with details
	OnetimePipelineConfigUpdates    []*CommandDetail       `protobuf:"bytes,5,rep,name=onetime_pipeline_config_updates,json=onetimePipelineConfigUpdates,proto3" json:"onetime_pipeline_config_updates,omitempty"`          // Agent's onetime pipeline config details
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *FetchConfigResponse) Reset() {
	*x = FetchConfigResponse{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigResponse) ProtoMessage() {}

func (x *FetchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigResponse.ProtoReflect.Descriptor instead.
func (*FetchConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{8}
}

func (x *FetchConfigResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *FetchConfigResponse) GetCommonResponse() *CommonResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

func (x *FetchConfigResponse) GetContinuousPipelineConfigUpdates() []*ConfigDetail {
	if x != nil {
		return x.ContinuousPipelineConfigUpdates
	}
	return nil
}

func (x *FetchConfigResponse) GetInstanceConfigUpdates() []*ConfigDetail {
	if x != nil {
		return x.InstanceConfigUpdates
	}
	return nil
}

func (x *FetchConfigResponse) GetOnetimePipelineConfigUpdates() []*CommandDetail {
	if x != nil {
		return x.OnetimePipelineConfigUpdates
	}
	return nil
}

// API: /Agent/ReportStatus
// optional api for report config status, but not wait util next heartbeat, see README.
// if HB server and Status server are different service, this api may be help.
type ReportStatusRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RequestId                 []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	InstanceId                []byte                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                // Agent's unique identification
	ContinuousPipelineConfigs []*ConfigInfo          `protobuf:"bytes,3,rep,name=continuous_pipeline_configs,json=continuousPipelineConfigs,proto3" json:"continuous_pipeline_configs,omitempty"` // status about the current continuous pipeline configs held by the Agent
	InstanceConfigs           []*ConfigInfo          `protobuf:"bytes,4,rep,name=instance_configs,json=instanceConfigs,proto3" json:"instance_configs,omitempty"`                                 // status about the current instance configs held by the Agent
	OnetimePipelineConfigs    []*ConfigInfo          `protobuf:"bytes,5,rep,name=onetime_pipeline_configs,json=onetimePipelineConfigs,proto3" json:"onetime_pipeline_configs,omitempty"`          // status about onetime pipeline configs history
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{9}
}

func (x *ReportStatusRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ReportStatusRequest) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *ReportStatusRequest) GetContinuousPipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.ContinuousPipelineConfigs
	}
	return nil
}

func (x *ReportStatusRequest) GetInstanceConfigs() []*ConfigInfo {
	if x != nil {
		return x.InstanceConfigs
	}
	return nil
}

func (x *ReportStatusRequest) GetOnetimePipelineConfigs() []*ConfigInfo {
	if x != nil {
		return x.OnetimePipelineConfigs
	}
	return nil
}

// ConfigServer response to Agent's report status request
type ReportStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CommonResponse *CommonResponse        `protobuf:"bytes,2,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{10}
}

func (x *ReportStatusResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ReportStatusResponse) GetCommonResponse() *CommonResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  []byte                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_proto_v2_agentV2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_agentV2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_v2_agentV2_proto_rawDescGZIP(), []int{11}
}

func (x *CommonResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommonResponse) GetErrorMessage() []byte {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

var File_proto_v2_agentV2_proto protoreflect.FileDescriptor

const file_proto_v2_agentV2_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v2/agentV2.proto\x12\x15configserver.proto.v2\"9\n" +
	"\rAgentGroupTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8f\x02\n" +
	"\n" +
	"ConfigInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.configserver.proto.v2.ConfigStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12B\n" +
	"\x05extra\x18\x05 \x03(\v2,.configserver.proto.v2.ConfigInfo.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x0fAgentAttributes\x12\x18\n" +
	"\aversion\x18\x01 \x01(\fR\aversion\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\fR\bhostname\x12\x16\n" +
	"\x06hostid\x18\x04 \x01(\fR\x06hostid\x12J\n" +
	"\x06extras\x18d \x03(\v22.configserver.proto.v2.AgentAttributes.ExtrasEntryR\x06extras\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc0\x05\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x04R\vsequenceNum\x12\"\n" +
	"\fcapabilities\x18\x03 \x01(\x04R\fcapabilities\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\fR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x05 \x01(\tR\tagentType\x12F\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2&.configserver.proto.v2.AgentAttributesR\n" +
	"attributes\x128\n" +
	"\x04tags\x18\a \x03(\v2$.configserver.proto.v2.AgentGroupTagR\x04tags\x12%\n" +
	"\x0erunning_status\x18\b \x01(\tR\rrunningStatus\x12!\n" +
	"\fstartup_time\x18\t \x01(\x03R\vstartupTime\x12a\n" +
	"\x1bcontinuous_pipeline_configs\x18\n" +
	" \x03(\v2!.configserver.proto.v2.ConfigInfoR\x19continuousPipelineConfigs\x12L\n" +
	"\x10instance_configs\x18\v \x03(\v2!.configserver.proto.v2.ConfigInfoR\x0finstanceConfigs\x12[\n" +
	"\x18onetime_pipeline_configs\x18\f \x03(\v2!.configserver.proto.v2.ConfigInfoR\x16onetimePipelineConfigs\x12\x14\n" +
	"\x05flags\x18\r \x01(\x04R\x05flags\x12\x16\n" +
	"\x06opaque\x18\x0e \x01(\fR\x06opaque\"\xd4\x01\n" +
	"\fConfigDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\fR\x06detail\x12D\n" +
	"\x05extra\x18\x04 \x03(\v2..configserver.proto.v2.ConfigDetail.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xdd\x01\n" +
	"\rCommandDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\fR\x06detail\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\x12E\n" +
	"\x05extra\x18\x04 \x03(\v2/.configserver.proto.v2.CommandDetail.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x90\x04\n" +
	"\x11HeartbeatResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12N\n" +
	"\x0fcommon_response\x18\x02 \x01(\v2%.configserver.proto.v2.CommonResponseR\x0ecommonResponse\x12\"\n" +
	"\fcapabilities\x18\x03 \x01(\x04R\fcapabilities\x12p\n" +
	"\"continuous_pipeline_config_updates\x18\x04 \x03(\v2#.configserver.proto.v2.ConfigDetailR\x1fcontinuousPipelineConfigUpdates\x12[\n" +
	"\x17instance_config_updates\x18\x05 \x03(\v2#.configserver.proto.v2.ConfigDetailR\x15instanceConfigUpdates\x12k\n" +
	"\x1fonetime_pipeline_config_updates\x18\x06 \x03(\v2$.configserver.proto.v2.CommandDetailR\x1conetimePipelineConfigUpdates\x12\x14\n" +
	"\x05flags\x18\a \x01(\x04R\x05flags\x12\x16\n" +
	"\x06opaque\x18\b \x01(\fR\x06opaque\"\xe2\x02\n" +
	"\x12FetchConfigRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\fR\n" +
	"instanceId\x12a\n" +
	"\x1bcontinuous_pipeline_configs\x18\x03 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x19continuousPipelineConfigs\x12L\n" +
	"\x10instance_configs\x18\x04 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x0finstanceConfigs\x12[\n" +
	"\x18onetime_pipeline_configs\x18\x05 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x16onetimePipelineConfigs\"\xc0\x03\n" +
	"\x13FetchConfigResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12N\n" +
	"\x0fcommon_response\x18\x02 \x01(\v2%.configserver.proto.v2.CommonResponseR\x0ecommonResponse\x12p\n" +
	"\"continuous_pipeline_config_updates\x18\x03 \x03(\v2#.configserver.proto.v2.ConfigDetailR\x1fcontinuousPipelineConfigUpdates\x12[\n" +
	"\x17instance_config_updates\x18\x04 \x03(\v2#.configserver.proto.v2.ConfigDetailR\x15instanceConfigUpdates\x12k\n" +
	"\x1fonetime_pipeline_config_updates\x18\x05 \x03(\v2$.configserver.proto.v2.CommandDetailR\x1conetimePipelineConfigUpdates\"\xe3\x02\n" +
	"\x13ReportStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\fR\n" +
	"instanceId\x12a\n" +
	"\x1bcontinuous_pipeline_configs\x18\x03 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x19continuousPipelineConfigs\x12L\n" +
	"\x10instance_configs\x18\x04 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x0finstanceConfigs\x12[\n" +
	"\x18onetime_pipeline_configs\x18\x05 \x03(\v2!.configserver.proto.v2.ConfigInfoR\x16onetimePipelineConfigs\"\x85\x01\n" +
	"\x14ReportStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12N\n" +
	"\x0fcommon_response\x18\x02 \x01(\v2%.configserver.proto.v2.CommonResponseR\x0ecommonResponse\"L\n" +
	"\x0eCommonResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\fR\ferrorMessage*@\n" +
	"\fConfigStatus\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\bAPPLYING\x10\x01\x12\v\n" +
	"\aAPPLIED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03*\x95\x01\n" +
	"\x11AgentCapabilities\x12\x1e\n" +
	"\x1aUnspecifiedAgentCapability\x10\x00\x12#\n" +
	"\x1fAcceptsContinuousPipelineConfig\x10\x01\x12\x19\n" +
	"\x15AcceptsInstanceConfig\x10\x02\x12 \n" +
	"\x1cAcceptsOnetimePipelineConfig\x10\x04*:\n" +
	"\fRequestFlags\x12\x1b\n" +
	"\x17RequestFlagsUnspecified\x10\x00\x12\r\n" +
	"\tFullState\x10\x01*\xbf\x01\n" +
	"\x12ServerCapabilities\x12\x1f\n" +
	"\x1bUnspecifiedServerCapability\x10\x00\x12\x14\n" +
	"\x10RembersAttribute\x10\x01\x12)\n" +
	"%RembersContinuousPipelineConfigStatus\x10\x02\x12\x1f\n" +
	"\x1bRembersInstanceConfigStatus\x10\x04\x12&\n" +
	"\"RembersOnetimePipelineConfigStatus\x10\b*\x8a\x01\n" +
	"\rResponseFlags\x12\x1c\n" +
	"\x18ResponseFlagsUnspecified\x10\x00\x12\x13\n" +
	"\x0fReportFullState\x10\x01\x12'\n" +
	"#FetchContinuousPipelineConfigDetail\x10\x02\x12\x1d\n" +
	"\x19FetchInstanceConfigDetail\x10\x04B<Z:github.com/alibaba/ilogtail/config_server/proto/v2;protov2b\x06proto3"

var (
	file_proto_v2_agentV2_proto_rawDescOnce sync.Once
	file_proto_v2_agentV2_proto_rawDescData []byte
)

func file_proto_v2_agentV2_proto_rawDescGZIP() []byte {
	file_proto_v2_agentV2_proto_rawDescOnce.Do(func() {
		file_proto_v2_agentV2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v2_agentV2_proto_rawDesc), len(file_proto_v2_agentV2_proto_rawDesc)))
	})
	return file_proto_v2_agentV2_proto_rawDescData
}

var file_proto_v2_agentV2_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_v2_agentV2_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_v2_agentV2_proto_goTypes = []any{
	(ConfigStatus)(0),            // 0: configserver.proto.v2.ConfigStatus
	(AgentCapabilities)(0),       // 1: configserver.proto.v2.AgentCapabilities
	(RequestFlags)(0),            // 2: configserver.proto.v2.RequestFlags
	(ServerCapabilities)(0),      // 3: configserver.proto.v2.ServerCapabilities
	(ResponseFlags)(0),           // 4: configserver.proto.v2.ResponseFlags
	(*AgentGroupTag)(nil),        // 5: configserver.proto.v2.AgentGroupTag
	(*ConfigInfo)(nil),           // 6: configserver.proto.v2.ConfigInfo
	(*AgentAttributes)(nil),      // 7: configserver.proto.v2.AgentAttributes
	(*HeartbeatRequest)(nil),     // 8: configserver.proto.v2.HeartbeatRequest
	(*ConfigDetail)(nil),         // 9: configserver.proto.v2.ConfigDetail
	(*CommandDetail)(nil),        // 10: configserver.proto.v2.CommandDetail
	(*HeartbeatResponse)(nil),    // 11: configserver.proto.v2.HeartbeatResponse
	(*FetchConfigRequest)(nil),   // 12: configserver.proto.v2.FetchConfigRequest
	(*FetchConfigResponse)(nil),  // 13: configserver.proto.v2.FetchConfigResponse
	(*ReportStatusRequest)(nil),  // 14: configserver.proto.v2.ReportStatusRequest
	(*ReportStatusResponse)(nil), // 15: configserver.proto.v2.ReportStatusResponse
	(*CommonResponse)(nil),       // 16: configserver.proto.v2.CommonResponse
	nil,                          // 17: configserver.proto.v2.ConfigInfo.ExtraEntry
	nil,                          // 18: configserver.proto.v2.AgentAttributes.ExtrasEntry
	nil,                          // 19: configserver.proto.v2.ConfigDetail.ExtraEntry
	nil,                          // 20: configserver.proto.v2.CommandDetail.ExtraEntry
}
var file_proto_v2_agentV2_proto_depIdxs = []int32{
	0,  // 0: configserver.proto.v2.ConfigInfo.status:type_name -> configserver.proto.v2.ConfigStatus
	17, // 1: configserver.proto.v2.ConfigInfo.extra:type_name -> configserver.proto.v2.ConfigInfo.ExtraEntry
	18, // 2: configserver.proto.v2.AgentAttributes.extras:type_name -> configserver.proto.v2.AgentAttributes.ExtrasEntry
	7,  // 3: configserver.proto.v2.HeartbeatRequest.attributes:type_name -> configserver.proto.v2.AgentAttributes
	5,  // 4: configserver.proto.v2.HeartbeatRequest.tags:type_name -> configserver.proto.v2.AgentGroupTag
	6,  // 5: configserver.proto.v2.HeartbeatRequest.continuous_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 6: configserver.proto.v2.HeartbeatRequest.instance_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 7: configserver.proto.v2.HeartbeatRequest.onetime_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	19, // 8: configserver.proto.v2.ConfigDetail.extra:type_name -> configserver.proto.v2.ConfigDetail.ExtraEntry
	20, // 9: configserver.proto.v2.CommandDetail.extra:type_name -> configserver.proto.v2.CommandDetail.ExtraEntry
	16, // 10: configserver.proto.v2.HeartbeatResponse.common_response:type_name -> configserver.proto.v2.CommonResponse
	9,  // 11: configserver.proto.v2.HeartbeatResponse.continuous_pipeline_config_updates:type_name -> configserver.proto.v2.ConfigDetail
	9,  // 12: configserver.proto.v2.HeartbeatResponse.instance_config_updates:type_name -> configserver.proto.v2.ConfigDetail
	10, // 13: configserver.proto.v2.HeartbeatResponse.onetime_pipeline_config_updates:type_name -> configserver.proto.v2.CommandDetail
	6,  // 14: configserver.proto.v2.FetchConfigRequest.continuous_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 15: configserver.proto.v2.FetchConfigRequest.instance_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 16: configserver.proto.v2.FetchConfigRequest.onetime_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	16, // 17: configserver.proto.v2.FetchConfigResponse.common_response:type_name -> configserver.proto.v2.CommonResponse
	9,  // 18: configserver.proto.v2.FetchConfigResponse.continuous_pipeline_config_updates:type_name -> configserver.proto.v2.ConfigDetail
	9,  // 19: configserver.proto.v2.FetchConfigResponse.instance_config_updates:type_name -> configserver.proto.v2.ConfigDetail
	10, // 20: configserver.proto.v2.FetchConfigResponse.onetime_pipeline_config_updates:type_name -> configserver.proto.v2.CommandDetail
	6,  // 21: configserver.proto.v2.ReportStatusRequest.continuous_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 22: configserver.proto.v2.ReportStatusRequest.instance_configs:type_name -> configserver.proto.v2.ConfigInfo
	6,  // 23: configserver.proto.v2.ReportStatusRequest.onetime_pipeline_configs:type_name -> configserver.proto.v2.ConfigInfo
	16, // 24: configserver.proto.v2.ReportStatusResponse.common_response:type_name -> configserver.proto.v2.CommonResponse
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_v2_agentV2_proto_init() }
func file_proto_v2_agentV2_proto_init() {
	if File_proto_v2_agentV2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v2_agentV2_proto_rawDesc), len(file_proto_v2_agentV2_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v2_agentV2_proto_goTypes,
		DependencyIndexes: file_proto_v2_agentV2_proto_depIdxs,
		EnumInfos:         file_proto_v2_agentV2_proto_enumTypes,
		MessageInfos:      file_proto_v2_agentV2_proto_msgTypes,
	}.Build()
	File_proto_v2_agentV2_proto = out.File
	file_proto_v2_agentV2_proto_goTypes = nil
	file_proto_v2_agentV2_proto_depIdxs = nil
}
